- hosts: web3
  gather_facts: no
  tasks:
  - name: installing httpd software
    package:
      name: "httpd"
      state: present

  - name: installing php software
    package:
      name: "php"
      state: present

  - name: copying webpage
    copy:
      src: "a.php"
      dest: "/var/www/html/index.php"
    notify: cpweb

  handlers:
  - name: cpweb
    service:
      name: "httpd"
      state: restarted


- hosts: lb
  gather_facts: no
  tasks:
  - name: installing haproxy software
    package:
      name: "haproxy"
      state: present

  - name: copying haproxy files
    template:
      src: "haproxy.cfg"
      dest: "/etc/haproxy/haproxy.cfg"
    notify: lbrestart

  handlers:
  - name: lbrestart
    service:
      name: "haproxy"
      state: restarted

